# Generated by Django 2.1.1 on 2018-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20181028_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='talktime',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
