# Generated by Django 2.1.1 on 2018-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_auto_20181028_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultcounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('counter', models.IntegerField()),
                ('D_fire', models.BooleanField(default=False)),
                ('D_blue', models.BooleanField(default=False)),
                ('D_germ', models.BooleanField(default=False)),
                ('D_moneyless', models.BooleanField(default=False)),
                ('D_stone', models.BooleanField(default=False)),
                ('D_sunburn', models.BooleanField(default=False)),
                ('D_fight', models.BooleanField(default=False)),
                ('D_sword', models.BooleanField(default=False)),
            ],
        ),
    ]
